# The Parlour Caretaker Configuration - The Parlour
logs_channel_id: 1220451817146683423 # Channel ID where moderation actions are logged
owner_ids: # User IDs of the bot owners
  - 411589337369804801
  - 398205938265358339
guild_id: 1151481698786213960 # Guild ID where the bot operates
dm_forward_channel_id: 1239669255012614267 # Channel ID for forwarding DMs
games_channel_id: 1159782202985426964 # Channel ID for sending games night announcements
gigchats_id: 1195097407604666399 # Channel ID for gig chats forum channel

statuses:
 - "The Killer ğŸ”ª"
 - "Burn Alive ğŸ¹"
 - "Godzilla ğŸ¦"
 - "Yeehaw Interlude ğŸ¤ "
 - "Portrait of a Dead Girl ğŸ¹"
 - "Nothing Matters ğŸ¹"
 - "Second Best ğŸ¥ˆ"
 - "Sinner ğŸ¹"
 - "Big Dog ğŸ•"
 - "Beautiful Boy ğŸ¹"
 - "Prelude to Ecstasy ğŸ¹"
 - "On Your Side ğŸ¹"
 - "Gjuha ğŸ¹"
 - "My Lady of Mercy ğŸ¹"
 - "Caesar on a TV Screen ğŸ¹"
 - "The Feminine Urge ğŸ¹"
 - "Mirror ğŸ¹"
