# The Parlour Caretaker Configuration - The Parlour Dev Server
logs_channel_id: 1237165394649682003 # Channel ID where moderation actions are logged
owner_ids: # User IDs of the bot owners
  - 411589337369804801
  - 398205938265358339
guild_id: 1161423690517463161 # Guild ID where the bot operates
dm_forward_channel_id: 1161423690517463164 # Channel ID for forwarding DMs
games_channel_id: 1281260171754082430 # Channel ID for sending games night announcements
gigchats_id: 1302737683537334332 # Channel ID for gig chats forum channel

statuses:
 - "Prelude to Ecstasy ğŸ¹"
 - "Burn Alive ğŸ¹"
 - "Caesar on a TV Screen ğŸ¹"
 - "The Feminine Urge ğŸ¹"
 - "On Your Side ğŸ¹"
 - "Beautiful Boy ğŸ¹"
 - "Gjuha ğŸ¹"
 - "Sinner ğŸ¹"
 - "My Lady of Mercy ğŸ¹"
 - "Portrait of a Dead Girl ğŸ¹"
 - "Nothing Matters ğŸ¹"
 - "Mirror ğŸ¹"
 - "Godzilla ğŸ¦"
 - "Big Dog ğŸ•"
 - "Second Best ğŸ¥ˆ"
 - "The Killer ğŸ”ª"
 - "Yeehaw Interlude ğŸ¤ "
