# ==========================
# The Parlour Caretaker Configuration - The Parlour
# ==========================

# --------------------------
# General Settings
# --------------------------
# List the user IDs of the bot owners.
owner_ids:
  - 411589337369804801   # Jay
  - 398205938265358339   # Harry

# Status messages to rotate through for the bot's presence.
statuses:
  - "Prelude to Ecstasy ğŸ¹"
  - "Burn Alive ğŸ¹"
  - "Caesar on a TV Screen ğŸ¹"
  - "The Feminine Urge ğŸ¹"
  - "On Your Side ğŸ¹"
  - "Beautiful Boy ğŸ¹"
  - "Gjuha ğŸ¹"
  - "Sinner ğŸ¹"
  - "My Lady of Mercy ğŸ¹"
  - "Portrait of a Dead Girl ğŸ¹"
  - "Nothing Matters ğŸ¹"
  - "Mirror ğŸ¹"
  - "Godzilla ğŸ¦"
  - "Big Dog ğŸ•"
  - "Second Best ğŸ¥ˆ"
  - "The Killer ğŸ”ª"
  - "Yeehaw Interlude ğŸ¤ "

# --------------------------
# Channel IDs
# --------------------------
# These are the channels used by the bot for various functions.
logs_channel_id: 1220451817146683423         # Channel where moderation actions are logged.
dm_forward_channel_id: 1239669255012614267    # Channel for forwarding direct messages.
games_channel_id: 1159782202985426964         # Channel for sending games night announcements.
gigchats_id: 1195097407604666399               # Channel for gig chats forum.
welcome_channel_id: 1151864993571160135        # Channel where welcome messages are posted.

# --------------------------
# Role Settings
# --------------------------
# Role to assign automatically to new joiners.
newjoin_role_id: 1151863422133227594           # Role ID to assign to new joiners.

# --------------------------
# Feature Toggles
# --------------------------
# Enable or disable specific features. Set to 'true' to enable the feature.
welcome_enabled: false     # Set to true to enable welcome messages.
autorole_enabled: false    # Set to true to enable auto role assignment.
